Bootstrap: docker
From: debian:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.github.com/pscedu/singularity-lazygit

%post
    apt update
    apt install -y git wget
    wget -nc https://github.com/jesseduffield/lazygit/releases/download/v0.28.2/lazygit_0.28.2_Linux_x86_64.tar.gz
    tar -xvf lazygit_0.28.2_Linux_x86_64.tar.gz
    mv lazygit /usr/local/bin
    rm -f README.md LICENSE lazygit_0.28.2_Linux_x86_64.tar.gz
